### ISSUE TITLE
HybPhyloMaker5_missingdataremovalNEW.sh

### ISSUE THREAD

**Issue by markusruhsam** [tomas-fer/HybPhyloMaker#12]
The script runs fine in the beginning until it comes to

> Calculating alignment conservation value for all genes using trimAl...
> Assembly_OG0006819.fasta
> 
> ERROR: Parameter "-sst" not valid.
> 
> awk: cmd. line:1: fatal: division by zero attempted

when it produces this error for all following genes. Seems that there is no -sst option in trimal so was wondering if that option relates to an older version. What does -sst specify and how can I get round the errors?

Thanks

Markus

**Comment by tomas-fer** [comment]
Dear Markus,
parameter "-sst" replaced the parameter "-sct" in trimAl v1.4. This version is recommended for running HybPhyloMaker (see Appendix 2 in manual)
Please check whether you are using trimAl v1.4 or, if using trimAl v1.2, change "-sst" to "-sct".
Hope this helps,
Tomas

**Comment by markusruhsam** [comment]
Hi Tomas,

I was using v1.2 and not v1.4 as recommended! Thanks very much for pointing this out. Script’s running fine now.

Best wishes

Markus

**Comment by tomas-fer** [comment]
Good to hear the issue was solves. Good luck with your analysis,
Tomas
