### ISSUE TITLE
HybPhyloMaker1_rawprocess.sh line 154

### ISSUE THREAD

**Issue by markusruhsam** [tomas-fer/HybPhyloMaker#13]
Hi Tomas,

I am running the rawprocess.sh script on a CentOS 8 machine and for some of my samples I get this 'line 154: killed' screen output.

```
Processing sample Hesperocyparis_sargentii_20090070X (31 out of 35)
Unzipping...
Removing PhiX...
Adapter removal & quality trimming...
Removing duplicates...
./HybPhyloMaker1_rawprocess.sh: line 154: 631351 Killed                  fastuniq -i fastqlist.txt -t q -o ${file}-1P_no-dups.fastq -p ${file}-2P_no-dups.fastq
cat: Hesperocyparis_sargentii_20090070X-1P_no-dups.fastq: No such file or directory
gzip: Hesperocyparis_sargentii_20090070X-1P_no-dups.fastq: No such file or directory
gzip: Hesperocyparis_sargentii_20090070X-2P_no-dups.fastq: No such file or directory
cp: cannot stat 'Hesperocyparis_sargentii_20090070X-1P_no-dups.fastq.gz': No such file or directory
cp: cannot stat 'Hesperocyparis_sargentii_20090070X-2P_no-dups.fastq.gz': No such file or directory

Processing sample Hesperocyparis_sargentii_E00189062A (32 out of 35)
Unzipping...
Removing PhiX...
Adapter removal & quality trimming...
Removing duplicates...

Processing sample Hesperocyparis_stephensonii_E00840947A (33 out of 35)
Unzipping...
Removing PhiX...
```
Not sure what this means and was wondering if this is something to worry about?

Thank you

Markus

**Comment by tomas-fer** [comment]
Dear Markus.

I have no idea what was the reason why the system killed the command.

But it looks like it happened only to some samples? These were then not processed (deduplicated etc.) and the data will be missing for subsequent scripts...

May be the sample is too big to be processed with your RAM amount etc. But I am just guessing.

Tomas

 

 

Od: markusruhsam [mailto:notifications@github.com] 
Odesláno: 16. srpna 2020 22:14
Komu: tomas-fer/HybPhyloMaker
Kopie: Subscribed
Předmět: [tomas-fer/HybPhyloMaker] HybPhyloMaker1_rawprocess.sh line 154 (#13)

 

Hi Tomas,

I am running the rawprocess.sh script on a CentOS 8 machine and for some of my samples I get this 'line 154: killed' screen output.

Processing sample Hesperocyparis_sargentii_20090070X (31 out of 35)
Unzipping...
Removing PhiX...
Adapter removal & quality trimming...
Removing duplicates...
./HybPhyloMaker1_rawprocess.sh: line 154: 631351 Killed                  fastuniq -i fastqlist.txt -t q -o ${file}-1P_no-dups.fastq -p ${file}-2P_no-dups.fastq
cat: Hesperocyparis_sargentii_20090070X-1P_no-dups.fastq: No such file or directory
gzip: Hesperocyparis_sargentii_20090070X-1P_no-dups.fastq: No such file or directory
gzip: Hesperocyparis_sargentii_20090070X-2P_no-dups.fastq: No such file or directory
cp: cannot stat 'Hesperocyparis_sargentii_20090070X-1P_no-dups.fastq.gz': No such file or directory
cp: cannot stat 'Hesperocyparis_sargentii_20090070X-2P_no-dups.fastq.gz': No such file or directory
 
Processing sample Hesperocyparis_sargentii_E00189062A (32 out of 35)
Unzipping...
Removing PhiX...
Adapter removal & quality trimming...
Removing duplicates...
 
Processing sample Hesperocyparis_stephensonii_E00840947A (33 out of 35)
Unzipping...
Removing PhiX...

Not sure what this means and was wondering if this is something to worry about?

Thank you

Markus

**Comment by markusruhsam** [comment]
Hi Tomas,

On a different server the same files finish without this funny error message. I compared the .log files from both servers for the samples with this error and noticed that only the 'duplicate-removal-fastuniq.log' files are different. The ones from the samples with the error have a lot fewer number of reads after duplicate removal.

`Nr. of reads before duplicate removal:
48583878
Nr. of reads after duplicate removal:
1158746`

`Nr. of reads before duplicate removal:
48583878
Nr. of reads after duplicate removal:
42109416`

And the '_no-dups-fastq.gz' files are missing.

File list with error

![image](https://user-images.githubusercontent.com/23214870/90403751-50e4a000-e099-11ea-9082-cbdbb6832ae5.png)

File list without error

![image](https://user-images.githubusercontent.com/23214870/90403881-825d6b80-e099-11ea-90ad-c88c85db8e6c.png)

So it seems that for some reason the fastuniq step doesn't produce the no-dups files for some samples. Strange. Anyway I suppose there's not much one can do about it except running the script on the less powerful but not producing an error server and copy the 'failed' samples to the other server in preparation for the next script.

**Comment by markusruhsam** [comment]
Hi Tomas,

It was a memory problem - just as you guessed. I've rerun the script without error using more CPUs and RAM. Thank uou.
