### ISSUE TITLE
./HybPhyloMaker1_rawprocess.sh: line 173:  Aborted

### ISSUE THREAD

**Issue by markusruhsam** [tomas-fer/HybPhyloMaker#16]
I get this error message when I run the rawprocess.sh script

![Capture](https://github.com/tomas-fer/HybPhyloMaker/assets/23214870/f245343c-57b6-4176-88d2-97915a6bfc07)

The PhiX-removal.log file shows that there seems to be a problem with BAM binary header

![Capture1](https://github.com/tomas-fer/HybPhyloMaker/assets/23214870/b42097b0-c43f-44d1-a7f6-521fa072da6e)

Any ideas what is happening there?

Thank you

Markus

**Comment by tomas-fer** [comment]
I have never seen this error. Could you send me a pair of fastq.gz files of one sample so I can try if I am able to replicate the issue?
What is in bowtie2.log?
BTW, you are violating file naming rules for HybPhyloMaker - sample names should follow this convention
Genus-species_code
with no additional ‘-‘ or ‘_’ in its name.
Only samples following this are processed smoothly.
So maybe first let’s try to change the name for one sample and run the script again.
Hope this helps, let me know, please.
Best,
Tomas

**Comment by markusruhsam** [comment]
I have renamed the files so that they follow the convention now

![Capture1](https://github.com/tomas-fer/HybPhyloMaker/assets/23214870/67ac36eb-1b05-422c-9f91-a52d9357a9a5)

but unfortunately I still get this error

![Capture](https://github.com/tomas-fer/HybPhyloMaker/assets/23214870/e9f103eb-ac98-4366-b64e-bcf16935abe0)

![Capture2](https://github.com/tomas-fer/HybPhyloMaker/assets/23214870/5568cd7b-76a4-4169-8011-85ab0a170148)

The bowtie2.log looks fine

![Capture](https://github.com/tomas-fer/HybPhyloMaker/assets/23214870/b15701d7-f74a-4f58-988d-2071be8819c7)

I also increased the memory to 128Gb using 8 CPUs so I suppose this shouldn't be due to a lack of memory...

**Comment by tomas-fer** [comment]
Dear Markus,
could you send me (or somehow share with me) one pair of your fastq.gz files?
I would try on my installation before checking further. Maybe it is a problem with newer versions of bowtie2, samtools and bam2fastq. Let me try.
Thanks,
Tomas

**Comment by markusruhsam** [comment]
Hi Tomas,

Just checking that you have received the link where you can download two files?

Thank you

Markus

**Comment by tomas-fer** [comment]
No, I am sorry, I did not get any link to download the data.
Could you resend it, please?
Tomas

**Comment by markusruhsam** [comment]
Is this the email address I should use to share the files  ***@***.******@***.***> ?

Thank you

Markus
