### ISSUE TITLE
‘partitions.txt’ could not be found

### ISSUE THREAD

**Issue by markusruhsam** [tomas-fer/HybPhyloMaker#17]
I finished running HybPhylomaker4a and got the error at the end that ‘partitions.txt’ could not be found.

![image](https://github.com/tomas-fer/HybPhyloMaker/assets/23214870/e775da0d-c6ec-4e33-a888-234c1f273ceb)

Checking the script partitions.txt seems to be produced by AMAS.py – python 3 is installed and the AMAS.py script is in HybSeqSource so I was wondering what the problem might be?

**Comment by tomas-fer** [comment]
Solved, the reason was an incorrectly formatted probe file (causing incompatibility with script 4).
