### ISSUE TITLE
Script6a error: "mv: cannot stat 'Assembly_OG000XXXX.part.reduced': No such file or directory"

### ISSUE THREAD

**Issue by markusruhsam** [tomas-fer/HybPhyloMaker#18]
Running HybPhyloMaker6a_RAxML_for_selected.sh I get this mv error for one gene after the other.

![image](https://github.com/tomas-fer/HybPhyloMaker/assets/23214870/c7d356dd-ddee-4503-a1ea-bef7148a027c)

Any help would be very much appreciated.

**Comment by tomas-fer** [comment]
This was just a warning message not affecting RAxML gene tree building. It is solved in v.1.8.0c of the script.
