### ISSUE TITLE
Issue order exons concatenated when 10 or more

### ISSUE THREAD

**Issue by Ptero64** [tomas-fer/HybPhyloMaker#6]
Hello,

I am using your pipeline for on my data and it's working well. However I had strange results for some of my genes when the number of exons is greater than 9 (in the fasta probes file).
Name in the file are like indicated in the manual:
>Assembly_GeneName_Contig_exonsNumber_wahtevernumber 
So:
>Assembly_A3GALT2_Contig_1_124
>Assembly_A3GALT2_Contig_2_115

But for genes with exons numbers superior to 9 (e.g. >Assembly_AAAS_Contig_12_204), exons are not concatenated in the correct order. For example for a gene with 10 exons. the sequence obtained start by exon 10 then 1 to 9. For another genes with more exons the order seems more random (10 - 11- 1 - 12).

Do you have an idea why I get this result? Is the naming I am using correct (not sure if Contig is mandatory and what you name exonsnumber). 
I thank you in advance for the help
Best regards

**Comment by tomas-fer** [comment]
Hi,
this issue is about how AMAS internally sorts files before concatenating when called with wildcard '*' in the file name. The solution would be to name all contigs with two numerals, e.g. 01, 02 etc.
BTW, does the exon order matter for your analysis?
Best,
Tomas

**Comment by Ptero64** [comment]
Hi,
Thanks for your answer. I made this change using 01-09 instead of 1-9 and it worked.
I have to recover the full coding sequences in the correct RF to do next selection test (PAML / Hyphy). 
Thanks
Best,
Nicolas

**Comment by tomas-fer** [comment]
An advice on exon numbering will be added to the next version of the manual. Closing issue. T
